"""Added books table

Revision ID: 045946dff1a1
Revises: afca2ad184da
Create Date: 2024-02-05 19:40:26.141434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "045946dff1a1"
down_revision = "afca2ad184da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=254), nullable=False),
        sa.Column("publishing_year", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=254), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_barcode"), "books", ["barcode"], unique=False)
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.drop_index("ix_author_name", table_name="author")
    op.create_index(op.f("ix_author_name"), "author", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_author_name"), table_name="author")
    op.create_index("ix_author_name", "author", ["name"], unique=False)
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_barcode"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
